MetaMask/contributor-docs

- README.md
- getting-started/README.md
- guides/README.md
- policies/README.md
- procedures/README.md
Directories have been setup for each category of contributor documentation, so that it's easier to start writing.
Each category has a single-sentence description that will be expanded later.
"(DRAFT)" has been added to each header to indicate that the document is not yet complete.
> Add initial documentation structure

- guides/guidelines.md
I feel that it would be good to have some amount of standardization around the documents that we add to this repo, at least when it comes to guidelines documents. These kinds of documents are basically souped up "do"s and "don't"s, and so it seems that we can assign a structure to them.
If we want something like this and feel that this belongs in `guides/README.md` then I'm happy to move it.
> Add guidelines for guidelines

- guides/guidelines.md
Some guidelines are more important to follow than others; some guidelines have alternatives which may be preferable depending on the circumstance. To clarify how guidelines ought to be followed, define importance levels/categories, and assign each guideline to one in the "meta" guidelines document as an example. These categories are borrowed from the [Redux Style Guide](https://redux.js.org/style-guide/#rule-categories). To prevent from having to create separate category sections in each guidelines document, I've opted to associate an emoji with each category.
> Add guideline categories

- guides/guidelines.md
There are a couple of issues with the "meta-guidelines":
1. Currently, if you want to assign a guideline to a category, you must
use an emoji in the guideline header. There are two problems with
emoji: they are difficult to work with — try selecting one in your
editor! — and, like icons, they can mean different things to
different people.
2. Originally we borrowed the concept of guideline categories from the
Redux Style Guide. This guide lists three of them: Essential,
Strongly Recommended (renamed to "Recommended" here), and Recommended
(renamed to "Suggested"). However, there is not a clear delineation
between these categories — when do you know whether to assign
something as Recommended vs. Essential? — and anyway, we've only used
the first and third categories so far.
3. The guideline …
> Update guidelines for guidelines

- guides/javascript.md
- guides/testing.md
- guides/typescript.md
These were copied from the notes that I've been keeping in Notion (see "Code Guidelines"). I tried to list best practices that I thought were already being followed in some form, so hopefully none of them should be too controversial.
Fixes #10.
[👉🏻 **See rendered JavaScript guidelines** 👈🏻](https://github.com/MetaMask/contributor-docs/blob/add-js-and-ts-guidelines/guides/javascript.md)
[👉🏻 **See rendered TypeScript guidelines** 👈🏻](https://github.com/MetaMask/contributor-docs/blob/add-js-and-ts-guidelines/guides/typescript.md)
> Add initial guidelines for JavaScript and TypeScript

- .editorconfig
We do not honor the line length for Markdown files that we typically use for code files in other repos. Some editors can show a marker at said line length, but in this case it is distracting. Although it's not a part of the EditorConfig spec, the `max_line_length` option is honored by some editors such as Vim and can be used to remove the marker. This commit sets that EditorConfig setting accordingly.
> Remove line length from Markdown files

- guides/guidelines.md
- guides/javascript.md
There is a notable overlap between the code guidelines in this repository and our ESLint rules. This talks about why guidelines are still useful in this context. It also removes the reference to "we" that slipped into a previous change.
> Explain connection to ESLint rules

- README.md
- getting-started/README.md
- guides/README.md
- policies/README.md
- procedures/README.md
This PR removes the draft text from the contributor docs section.
> chore: remove all DRAFT text from contributor docs

- .gitignore
- docs/sdlc.md
Since all Markdown files got moved into `docs/` they haven't been getting linted. This is because `docs/` is in the `.gitignore` file, and we configure Prettier to honor that. This removes `docs/` from that file so that Prettier will see all files there.
> Lint Markdown files in docs/

- docs/pull-requests.md
The current pull request merge guidelines are a bit misleading in how the default Squash & Merge commit message is generated. It has been updated to clarify that the default message is configurable in the repository settings, so it can differ between repositories.
The advice has been scaled back a bit as well. Given the different circumstances, I wasn't sure what exactly to advise so I have removed the suggestion to edit the message for now. I'd like us to discuss standardizing on one of the default commit message choices, then we can revisit this guideline.
A recommendation has been added about leaving the default title unaltered though. Altering it could break some of our scripts.
> Update pull request merge guidelines

- README.md
- docs/secure-coding-guidelines.md
This PR adds secure coding guidelines base on concepts from OWASP Top Ten and modified to the specific at MetaMask when developing client application and libraries. 
[Link to formatted version](https://github.com/MetaMask/contributor-docs/blob/chore/secure-coding-guidelines/docs/secure-coding-guidelines.md)
> docs: v1 secure coding guidelines

- README.md
The Secure Coding Guidelines document path in the table of contents is broken. The path has been updated and is valid.
> fix: the secure coding doc path

- docs/pull-requests.md
The pull request guidelines have been updated to consistently use the term "issue" to refer to a GitHub issue, rather than "ticket". Our team calls them issues more often, "ticket" might be unfamiliar to some people.
A minor typo (an extra word) has been fixed in the second section that was affected as well.
> chore: Normalize terminology from ticket to issue

- docs/secure-coding-guidelines.md
Two examples have been added that explain in further detail how to properly document that you've reviewed a Socket.dev warning.
This is an improvement suggested in this comment: https://github.com/MetaMask/contributor-docs/pull/58#discussion_r1394011196
> feat: Add examples of how to resolve a Socket.dev warning

- docs/unit-testing.md
The `describe` block was incorrect, and the examples needed a bit more explanation.
> Fix 'Highlight exercise phase' example

- docs/secure-coding-guidelines.md
The `allow-scripts` instructions now defer to the `allow-scripts` README for setup instructions. Additionally, there is now a bit more guidance on how to decide whether to allow a script.
> feat: Improve `allow-scripts` instructions

- docs/testing/overview.md
A section has been added to the "Testing Overview" document to describe our testing principles. These establish what the goals of our automated test suite are, and help contributors differentiate between good and bad tests.
[Rendered](https://github.com/MetaMask/contributor-docs/blob/document-testing-purpose/docs/testing/overview.md)
> feat: Add testing principles

- docs/performance-tracing.md
The main branch of the `metamask-extension` repository was recently renamed from `develop` to `main`. This updates a link to point to the correct branch.
> chore: Rename reference to extension main branch

- docs/migrations-guidelines.md
- docs/pull-requests.md
- docs/testing/e2e/extension-e2e-guidelines.md
This pull request addresses several minor typos and grammatical issues in multiple documentation files:
1. Fixed incorrect use of "a" instead of "an" in the "migrations-guidelines.md" file.
2. Corrected the hyphenation of "up to date" in the "pull-requests.md" file.
3. Corrected the article usage ("a" to "an") in the "extension-e2e-guidelines.md" file.
These changes enhance the clarity and correctness of the documentation.
No specific issue fixed, general documentation improvement.
[Link to the preview](#) (if applicable)
> Fix typos and improve clarity in documentation files

- docs/migrations-guidelines.md
- docs/testing/e2e/extension-e2e-guidelines.md
- examples/extension-e2e-page-object-model/login.flow.ts
- `"intial"` → `"initial"`  
- `"recommanded"` → `"recommended"`
- `"pasword"` → `"password"`
> Fix spelling errors

- docs/remote-feature-flags.md
- docs/testing/e2e/mobile-e2e-mocking.md
Fix: https://github.com/MetaMask/MetaMask-planning/issues/4186
Create a documentation to explain other teams how to use remote feature flags.
This also includes the documentation from mobile side by @joaoloureirop 🙏🏻 
https://www.notion.so/metamask-consensys/Remote-feature-flags-with-Launch-Darkly-197f86d67d6880be86ffecbd313f62cf
> feat(4186): add doc for remote feature flag

- docs/remote-feature-flags.md
Modify the e2e config for local remote feature flag
> fix: modify example for e2e tests in remote feature flag

- docs/performance-dashboard.md
Fixed: 
- "dasboard" → "dashboard" 
- "self explanatory" → "self-explanatory"
- "you metric" → "your metric" 
- "y-axis-congig" → "y-axis-config"
>  Fix typos and improve readability in `performance-dashboard.md`
